### ISSUE TITLE
Load .po file directly

### ISSUE THREAD

**Issue by JuKu** [awkay/easy-i18n#10]
Hi again,

Is it possible to load a .po file directly, i mean without compiling this files to resource bundles?

**Comment by Shredder121** [comment]
No, a .po file is specifically for humans.
There's some tooling around it, but you get a resulting .po file back.
For runtime usage it needs to be compiled.

**Comment by awkay** [comment]
The compiled file is required.

**Comment by JuKu** [comment]
@Shredder121 @awkay Thanks for your fast answers!
