### ISSUE TITLE
Multiple translation packages

### ISSUE THREAD

**Issue by ohanssen** [awkay/easy-i18n#3]
I do translation for an application. That application can run plugins provided by independent authors which should also do translation. I guess the plugins need to have their own packages for translations. Is this supported or is it a good idea to do so?

**Comment by awkay** [comment]
Hi,

I'm sorry, but that particular use-case was not considered in the design,
and it is not supported. The system is build around the idea that there
will be one vendor in control of the entire application, and one
translation file for the entire source base.

That said, your plugin provider could provide translations that could be
merged into the software system, but this would require all of the plugin
vendors to pre-supply translations, and would therefore be difficult to
manage.

Tony
